### ISSUE TITLE
Broken Link in release notes

### ISSUE THREAD

**Issue by natalihu** [AdobeDocs/release-notes.en#15]
Issue in ./current.md  

https://experienceleague.adobe.com/docs/release-notes/experience-cloud/current.html?lang=en#status

Data Feed and Data Warehouse IP Address Changes | April 6, 2021
-- | --

The below is a link that is broken.

 Here is a full list of IP Address ranges to place into your firewall’s allow lists.

**Comment by bbringhu** [comment]
The broken link was fixed and pushed live.

The link URL mistakenly started with 'https://https://'.
